image: node:14.9.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - npm test
  only:
    - branches

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
  only:
    - master
